name: Monitor Google Careers Page

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Restore cached hash and content
      uses: actions/cache@v3
      with:
        path: |
          page_hash.txt
          previous_content.txt
        key: job-monitor-hash-restore
        restore-keys: |
          job-monitor-hash-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run monitor script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python job_monitor.py

    - name: Save updated hash and content to new cache
      if: always()
      uses: actions/cache/save@v3
      with:
        path: |
          page_hash.txt
          previous_content.txt
        key: job-monitor-hash-${{ github.run_id }}
